repos:
  - repo: local
    hooks:
      - id: black
        name: black
        entry: black
        language: python_venv
        pass_filenames: true
        fail_fast: false
        types:
          - python

      - id: isort
        name: isort
        entry: isort
        language: python_venv
        pass_filenames: true
        fail_fast: false
        types:
          - python

      - id: pyupgrade
        name: pyupgrade
        entry: pyupgrade
        language: python_venv
        pass_filenames: true
        fail_fast: false
        types:
          - python

      - id: ruff
        name: ruff
        entry: ruff
        language: python_venv
        pass_filenames: true
        types:
          - python
