repos:
  - repo: local
    hooks:
      - id: black
        name: black
        entry: black
        language: system
        pass_filenames: true
        types:
          - python

      - id: isort
        name: isort
        entry: isort
        language: system
        pass_filenames: true
        types:
          - python


  - repo: https://github.com/asottile/pyupgrade
    rev: v3.3.1
    hooks:
      - id: pyupgrade
        types:
        - python

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: 'v0.0.224'
    hooks:
      - id: ruff
        args: [ "--force-exclude" ]
        types:
          - python