repos:
  - repo: local
    hooks:
      - id: black
        name: black
        entry: black
        always_run: true
        language: system
        pass_filenames: false
        fail_fast: true
        args:
          [
            ".",
            "--check",
            "--diff",
          ]

      - id: isort
        name: isort
        entry: isort
        always_run: true
        language: system
        pass_filenames: false
        fail_fast: true
        args:
          [
            ".",
            "--check",
            "--diff",
          ]

  - repo: https://github.com/asottile/pyupgrade
    rev: v3.3.1
    hooks:
      - id: pyupgrade

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: 'v0.0.224'
    hooks:
      - id: ruff
        args: [ "--force-exclude" ]