repos:
  - repo: local
    hooks:
      - id: black
        name: black
        entry: black
        language: python_venv
        pass_filenames: true
        fail_fast: false
        additional_dependencies: [black==23.3.0]
        types:
          - python

      - id: isort
        name: isort
        entry: isort
        language: python_venv
        pass_filenames: true
        fail_fast: false
        additional_dependencies: [isort==5.12.0]
        types:
          - python

      - id: pyupgrade
        name: pyupgrade
        entry: pyupgrade
        language: python_venv
        pass_filenames: true
        fail_fast: false
        additional_dependencies: [pyupgrade==3.6.0]
        types:
          - python

      - id: ruff
        name: ruff
        entry: ruff
        language: python_venv
        pass_filenames: true
        fail_fast: false
        additional_dependencies: [ruff==0.0.272]
        types:
          - python
