[nameless]
version = "2025.01.17"
description = "Just a normal bot."
support_server = ""

[blacklist]
users = []
guilds = []

[[wavelinks]]
name = "default"
uri = "http://localhost:2333"
password = "youshallnotpass"
is_default = true
autostart = true
