[tool.basedpyright]
exclude = ["venv", ".venv", "**/__pycache__"]
reportUnnecessaryTypeIgnoreComment = "error"
reportMissingImports = "error"
reportMissingTypeStubs = "none"
reportImportCycles = true
reportUnusedCallResult = false
typeCheckingMode = "recommended"

[tool.ruff]
line-length = 120
indent-width = 4
fix = true
exclude = [
    ".git",
    ".ruff_cache",
    ".venv",
    "venv",
    "__pypackages__",
    "__pycache__",
]

[tool.ruff.format]
indent-style = "space"

[tool.ruff.lint]
select = ["E", "F", "UP", "B", "SIM", "I", "Q"]

[tool.ruff.lint.per-file-ignores]
"__init__.py" = ["E402", "F401", "F403"]
