[tool.pyright]
exclude = [
    "venv",
    ".venv",
    "alembic",
    "**/__pycache__",
]

reportWildcardImportFromLibrary = "warning"
reportUnnecessaryTypeIgnoreComment = "error"
reportOptionalMemberAccess = "warning"
reportOptionalSubscript = "warning"
useLibraryCodeForTypes = true
pythonVersion = "3.11"
typeCheckingMode = "basic"

[tool.ruff]
line-length = 120
indent-width = 4
target-version = "py311"
fix = true
ignore = ["E999"]
select = ["E", "F", "Q"]
exclude = [
    ".git",
    "alembic",
    ".mypy_cache",
    ".ruff_cache",
    ".venv",
    "__pypackages__",
    "__pycache__",
    "venv",
]

[tool.ruff.per-file-ignores]
"__init__.py" = ["E402", "F401", "F403"]
"nameless/database/models.py" = ["F403", "F405"]
"nameless/cogs/ModeratorCog.py" = ["E999"]
"NamelessConfig_example.py" = ["SIM115"]

[tool.ruff.format]
indent-style = "space"

[tool.ruff.lint]
select = ["E", "F", "UP", "B", "SIM", "I",]
