[tool.pyright]
exclude = ["venv", ".venv", "**/__pycache__"]
reportWildcardImportFromLibrary = "none"
reportUnnecessaryTypeIgnoreComment = "error"
reportOptionalMemberAccess = "warning"
reportOptionalSubscript = "warning"
reportUnusedCallResult = false
useLibraryCodeForTypes = true
typeCheckingMode = "strict"

[tool.ruff]
line-length = 120
indent-width = 4
fix = true
exclude = [
    ".git",
    ".ruff_cache",
    ".venv",
    "venv",
    "__pypackages__",
    "__pycache__",
]

[tool.ruff.format]
indent-style = "space"

[tool.ruff.lint]
select = ["E", "F", "UP", "B", "SIM", "I", "Q"]

[tool.ruff.lint.per-file-ignores]
"__init__.py" = ["E402", "F401", "F403"]
