[tool.pyright]
exclude = [
    "venv",
    ".venv",
    "alembic",
    "**/__pycache__",
]

reportUnnecessaryTypeIgnoreComment = "warning"
reportOptionalMemberAccess = "warning"
reportOptionalSubscript = "warning"
reportUnusedImport = "error"
useLibraryCodeForTypes = true
pythonVersion = "3.10"
typeCheckingMode = "basic"

[tool.isort]
profile = "black"
combine_as_imports = true
combine_star = true
line_length = 120
lines_after_imports = 2
multi_line_output = 3

[tool.black]
line-length = 120
target-version = ['py310']
include = '\.pyi?$'

[tool.ruff]
line-length = 120
target-version = "py310"
fix = true
ignore = ["E999"]
select = ["E", "F", "Q"]
exclude = [
    ".git",
    "alembic",
    ".mypy_cache",
    ".ruff_cache",
    ".venv",
    "__pypackages__",
    "__pycache__",
    "venv",
]

[tool.ruff.per-file-ignores]
"__init__.py" = ["E402", "F401", "F403"]
"nameless/database/models.py" = ["F403", "F405"]
"nameless/cogs/ModeratorCog.py" = ["E999"]
