name: Lint and test code

on:
  push:
    branches:
      - 'feat/**'
      - 'fix/**'
      - 'main'
    tags-ignore:
      - '*'
  pull_request:
    branches:
      - 'feat/**'
      - 'fix/**'
      - 'main'

jobs:
  python:
    if: ${{ github.repository == 'nameless-on-discord/nameless' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install --upgrade setuptools wheel
          pip install -U -r requirements_core.txt -r requirements_dev.txt

      - name: Create dummy config file
        run: |
          cp NamelessConfig_example.py NamelessConfig.py

      - name: Code format checking (black)
        run: |
          black . --check --diff

      - name: Code format checking (isort)
        run: |
          isort . --check --diff

      - name: Type annotation checking (pyright)
        run: |
          pyright

      - name: Linting (ruff)
        run: |
          ruff nameless main.py NamelessConfig_example.py

      - name: Non-modern code check (pyupgrade)
        run: |
          pyupgrade --py310-plus nameless/*.py

      - name: Run tests and return coverages (pytest & friends)
        run: |
          pytest --cov-report term-missing --cov=nameless.database --cov=nameless.commons.Utility tests/
