name: Create experimental release (every week)

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 1,7,14,21,28 * *"

permissions:
  contents: write

jobs:
  release-stable:
    runs-on: ubuntu-latest
    steps:
      - name: Create stable release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "experimental"
          prerelease: false
          title: "Experimental release of nameless*"
