name: Create stable release (14th and 28th day of the month)

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 14,28 * *"

permissions:
  contents: write

jobs:
  release-stable:
    runs-on: ubuntu-latest
    steps:
      - name: Create stable release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "stable"
          prerelease: false
          title: "Stable release of nameless*"
