name: Validate pushes to official nameless* branch(es)

on:
  push:
    branches:
      - "main"
      - "fix/**"
      - "feat/**"

permissions:
  contents: write

jobs:
  python:
    if: ${{ github.repository == 'team-nameless/nameless-discord-bot' }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.13"]

    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT }}

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"
          cache-dependency-path: |
            **/requirements*.txt

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install --upgrade setuptools wheel
          pip install -U -r requirements.txt -r requirements.dev.txt

      - name: Fix the code with ruff
        run: |
          ruff check --select I --fix --exit-zero .
          ruff check --select UP --fix --exit-zero .
          ruff check --fix --exit-zero .
          ruff format .

      - name: Type checking with BasedPyright
        run: |
          basedpyright

      - name: Push the formatted code if needed.
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "[ci skip] Automated code format commit."
