name: Code validation

on:
  push:
    branches:
      - 'feat/**'
      - 'fix/**'
      - 'main'

jobs:
  python:
    if: ${{ github.repository == 'team-nameless/nameless-discord-bot' }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11", "3.12"]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"
          cache-dependency-path: |
            **/requirements*.txt

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install --upgrade setuptools wheel
          pip install -U -r requirements_core.txt -r requirements_dev.txt

      - name: Create dummy config file
        run: |
          cp NamelessConfig_example.py NamelessConfig.py

      - name: Check the code with ruff
        run: |
          ruff check . --diff
          ruff format . --diff

      - name: Type checking with PyWrong
        run: |
          pyright

      - name: Run tests and return coverages (pytest & friends)
        run: |
          pytest --cov-report term-missing --cov=nameless.database --cov=nameless.commons.Utility tests/
