name: Lint and test code

on:
  push:
    branches:
      - 'feat/**'
      - 'fix/**'
      - 'main'
  pull_request:
    branches:
      - 'feat/**'
      - 'fix/**'
      - 'main'

permissions:
  contents: write

jobs:
  python:
    if: ${{ github.repository == 'team-nameless/nameless-discord-bot' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install --upgrade setuptools wheel
          pip install -U -r requirements_core.txt -r requirements_dev.txt

      - name: Create dummy config file
        run: |
          cp NamelessConfig_example.py NamelessConfig.py

      - name: Fix the code with ruff
        run: |
          ruff check --select I --fix --exit-zero .
          ruff check --select UP --fix --exit-zero .
          ruff check --fix --exit-zero .
          ruff format .

      - name: Update nameless version file with the --version flag
        run: |
          python -m main --version

      - name: Run tests and return coverages (pytest & friends)
        run: |
          pytest --cov-report term-missing --cov=nameless.database --cov=nameless.commons.Utility tests/

      - name: Delete the dummy config file
        run: |
           rm NamelessConfig.py

      - name: Push the changes if needed.
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Automated code format commit."