name: Create experimental release on demand

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  jar:
    runs-on: ubuntu-latest
    steps:
      - name: Create experimental release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "experimental"
          prerelease: true
          title: "Experimental release of nameless*"
